name: "PR Title Checker"
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - labeled
      - unlabeled

jobs:
  titleCheck:
    runs-on: ubuntu-latest
    steps:
      - id: title_check
        name: check pr title for keyword
        uses: thehanimo/pr-title-checker@v1.3.4
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          pass_on_octokit_error: false
          configuration_path: ".github/pr-title.json"
  labelCheck:
    runs-on: ubuntu-latest
    needs: [ titleCheck ]
#    this check not working
#     if: needs.steps.title_check.result == 'y'
    steps:
      - name: check label
        run: echo needs.steps.title_check
