name: "PR Title Checker"
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - labeled
      - unlabeled

jobs:
  titleCheck:
    runs-on: ubuntu-latest
    steps:
      - id: title_check
        name: check pr title for keyword
        uses: smzelek/pr-title-checker@dev
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          pass_on_octokit_error: false
          configuration_path: ".github/pr-title-checker-config.json"
  labelCheck:
    runs-on: ubuntu-latest
    needs: [ titleCheck ]
#    this check not working
#     if: needs.steps.title_check.result == 'y'
    steps:
      - name: check label
        shell: bash
        run: |
          echo "GH_NEEDS: $GH_NEEDS"
          echo "GH_STEPS: $GH_STEPS"
          echo "GH_C: $GH_C"
        env:
          GH_NEEDS: ${{ toJSON(needs) }}
          GH_STEPS: ${{ toJSON(steps) }}
          GH_C: ${{ toJSON(github) }}
